revoke delete on table "public"."registration" from "anon";

revoke insert on table "public"."registration" from "anon";

revoke references on table "public"."registration" from "anon";

revoke select on table "public"."registration" from "anon";

revoke trigger on table "public"."registration" from "anon";

revoke truncate on table "public"."registration" from "anon";

revoke update on table "public"."registration" from "anon";

revoke delete on table "public"."registration" from "authenticated";

revoke insert on table "public"."registration" from "authenticated";

revoke references on table "public"."registration" from "authenticated";

revoke select on table "public"."registration" from "authenticated";

revoke trigger on table "public"."registration" from "authenticated";

revoke truncate on table "public"."registration" from "authenticated";

revoke update on table "public"."registration" from "authenticated";

revoke delete on table "public"."registration" from "service_role";

revoke insert on table "public"."registration" from "service_role";

revoke references on table "public"."registration" from "service_role";

revoke select on table "public"."registration" from "service_role";

revoke trigger on table "public"."registration" from "service_role";

revoke truncate on table "public"."registration" from "service_role";

revoke update on table "public"."registration" from "service_role";

alter table "public"."registration" drop constraint "registration_course_id_fkey";

alter table "public"."registration" drop constraint "registration_student_id_fkey";

alter table "public"."registration" drop constraint "registration_pkey";

drop index if exists "public"."registration_pkey";

drop table "public"."registration";

create table "public"."enrollment" (
    "id" bigint generated by default as identity not null,
    "student_id" bigint not null,
    "course_id" bigint not null,
    "enrollment_date" timestamp with time zone not null default now()
);


alter table "public"."enrollment" enable row level security;

CREATE UNIQUE INDEX registration_pkey ON public.enrollment USING btree (id);

alter table "public"."enrollment" add constraint "registration_pkey" PRIMARY KEY using index "registration_pkey";

alter table "public"."enrollment" add constraint "registration_course_id_fkey" FOREIGN KEY (course_id) REFERENCES course(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."enrollment" validate constraint "registration_course_id_fkey";

alter table "public"."enrollment" add constraint "registration_student_id_fkey" FOREIGN KEY (student_id) REFERENCES student(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."enrollment" validate constraint "registration_student_id_fkey";

grant delete on table "public"."enrollment" to "anon";

grant insert on table "public"."enrollment" to "anon";

grant references on table "public"."enrollment" to "anon";

grant select on table "public"."enrollment" to "anon";

grant trigger on table "public"."enrollment" to "anon";

grant truncate on table "public"."enrollment" to "anon";

grant update on table "public"."enrollment" to "anon";

grant delete on table "public"."enrollment" to "authenticated";

grant insert on table "public"."enrollment" to "authenticated";

grant references on table "public"."enrollment" to "authenticated";

grant select on table "public"."enrollment" to "authenticated";

grant trigger on table "public"."enrollment" to "authenticated";

grant truncate on table "public"."enrollment" to "authenticated";

grant update on table "public"."enrollment" to "authenticated";

grant delete on table "public"."enrollment" to "service_role";

grant insert on table "public"."enrollment" to "service_role";

grant references on table "public"."enrollment" to "service_role";

grant select on table "public"."enrollment" to "service_role";

grant trigger on table "public"."enrollment" to "service_role";

grant truncate on table "public"."enrollment" to "service_role";

grant update on table "public"."enrollment" to "service_role";


