create table "public"."course" (
    "id" bigint generated by default as identity not null,
    "code" character varying not null,
    "name" character varying not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."course" enable row level security;

create table "public"."registration" (
    "id" bigint generated by default as identity not null,
    "student_id" bigint not null,
    "course_id" bigint not null,
    "registered_at" timestamp with time zone not null default now()
);


alter table "public"."registration" enable row level security;

create table "public"."student" (
    "id" bigint generated by default as identity not null,
    "first_name" character varying not null,
    "last_name" character varying not null,
    "gender" character varying not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."student" enable row level security;

CREATE UNIQUE INDEX course_code_key ON public.course USING btree (code);

CREATE UNIQUE INDEX course_pkey ON public.course USING btree (id);

CREATE UNIQUE INDEX registration_pkey ON public.registration USING btree (id);

CREATE UNIQUE INDEX student_pkey ON public.student USING btree (id);

alter table "public"."course" add constraint "course_pkey" PRIMARY KEY using index "course_pkey";

alter table "public"."registration" add constraint "registration_pkey" PRIMARY KEY using index "registration_pkey";

alter table "public"."student" add constraint "student_pkey" PRIMARY KEY using index "student_pkey";

alter table "public"."course" add constraint "course_code_key" UNIQUE using index "course_code_key";

alter table "public"."registration" add constraint "registration_course_id_fkey" FOREIGN KEY (course_id) REFERENCES course(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."registration" validate constraint "registration_course_id_fkey";

alter table "public"."registration" add constraint "registration_student_id_fkey" FOREIGN KEY (student_id) REFERENCES student(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."registration" validate constraint "registration_student_id_fkey";

grant delete on table "public"."course" to "anon";

grant insert on table "public"."course" to "anon";

grant references on table "public"."course" to "anon";

grant select on table "public"."course" to "anon";

grant trigger on table "public"."course" to "anon";

grant truncate on table "public"."course" to "anon";

grant update on table "public"."course" to "anon";

grant delete on table "public"."course" to "authenticated";

grant insert on table "public"."course" to "authenticated";

grant references on table "public"."course" to "authenticated";

grant select on table "public"."course" to "authenticated";

grant trigger on table "public"."course" to "authenticated";

grant truncate on table "public"."course" to "authenticated";

grant update on table "public"."course" to "authenticated";

grant delete on table "public"."course" to "service_role";

grant insert on table "public"."course" to "service_role";

grant references on table "public"."course" to "service_role";

grant select on table "public"."course" to "service_role";

grant trigger on table "public"."course" to "service_role";

grant truncate on table "public"."course" to "service_role";

grant update on table "public"."course" to "service_role";

grant delete on table "public"."registration" to "anon";

grant insert on table "public"."registration" to "anon";

grant references on table "public"."registration" to "anon";

grant select on table "public"."registration" to "anon";

grant trigger on table "public"."registration" to "anon";

grant truncate on table "public"."registration" to "anon";

grant update on table "public"."registration" to "anon";

grant delete on table "public"."registration" to "authenticated";

grant insert on table "public"."registration" to "authenticated";

grant references on table "public"."registration" to "authenticated";

grant select on table "public"."registration" to "authenticated";

grant trigger on table "public"."registration" to "authenticated";

grant truncate on table "public"."registration" to "authenticated";

grant update on table "public"."registration" to "authenticated";

grant delete on table "public"."registration" to "service_role";

grant insert on table "public"."registration" to "service_role";

grant references on table "public"."registration" to "service_role";

grant select on table "public"."registration" to "service_role";

grant trigger on table "public"."registration" to "service_role";

grant truncate on table "public"."registration" to "service_role";

grant update on table "public"."registration" to "service_role";

grant delete on table "public"."student" to "anon";

grant insert on table "public"."student" to "anon";

grant references on table "public"."student" to "anon";

grant select on table "public"."student" to "anon";

grant trigger on table "public"."student" to "anon";

grant truncate on table "public"."student" to "anon";

grant update on table "public"."student" to "anon";

grant delete on table "public"."student" to "authenticated";

grant insert on table "public"."student" to "authenticated";

grant references on table "public"."student" to "authenticated";

grant select on table "public"."student" to "authenticated";

grant trigger on table "public"."student" to "authenticated";

grant truncate on table "public"."student" to "authenticated";

grant update on table "public"."student" to "authenticated";

grant delete on table "public"."student" to "service_role";

grant insert on table "public"."student" to "service_role";

grant references on table "public"."student" to "service_role";

grant select on table "public"."student" to "service_role";

grant trigger on table "public"."student" to "service_role";

grant truncate on table "public"."student" to "service_role";

grant update on table "public"."student" to "service_role";


