create table "public"."academic_year" (
    "id" bigint generated by default as identity not null,
    "year_label" character varying not null,
    "start_date" date not null,
    "end_date" date not null
);


alter table "public"."academic_year" enable row level security;

create table "public"."course" (
    "id" bigint generated by default as identity not null,
    "code" character varying not null,
    "name" character varying not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."course" enable row level security;

create table "public"."course_offering" (
    "id" bigint generated by default as identity not null,
    "course_id" bigint not null,
    "term_id" bigint not null
);


alter table "public"."course_offering" enable row level security;

create table "public"."enrollment" (
    "id" bigint generated by default as identity not null,
    "student_id" bigint not null,
    "course_id" bigint not null,
    "enrollment_date" timestamp with time zone not null default now()
);


alter table "public"."enrollment" enable row level security;

create table "public"."student" (
    "id" bigint generated by default as identity not null,
    "first_name" character varying not null,
    "last_name" character varying not null,
    "gender" character varying not null,
    "created_at" timestamp with time zone not null default now(),
    "gov_id" character varying(11) not null
);


alter table "public"."student" enable row level security;

create table "public"."term" (
    "id" bigint generated by default as identity not null,
    "academic_year_id" bigint,
    "term_name" character varying,
    "registration_open" date not null,
    "registration_close" date not null
);


alter table "public"."term" enable row level security;

CREATE UNIQUE INDEX academic_year_pkey ON public.academic_year USING btree (id);

CREATE UNIQUE INDEX course_code_key ON public.course USING btree (code);

CREATE UNIQUE INDEX course_offering_pkey ON public.course_offering USING btree (id);

CREATE UNIQUE INDEX course_pkey ON public.course USING btree (id);

CREATE UNIQUE INDEX registration_pkey ON public.enrollment USING btree (id);

CREATE UNIQUE INDEX student_pkey ON public.student USING btree (id);

CREATE UNIQUE INDEX term_pkey ON public.term USING btree (id);

CREATE UNIQUE INDEX uq_student_gov_id ON public.student USING btree (gov_id);

alter table "public"."academic_year" add constraint "academic_year_pkey" PRIMARY KEY using index "academic_year_pkey";

alter table "public"."course" add constraint "course_pkey" PRIMARY KEY using index "course_pkey";

alter table "public"."course_offering" add constraint "course_offering_pkey" PRIMARY KEY using index "course_offering_pkey";

alter table "public"."enrollment" add constraint "registration_pkey" PRIMARY KEY using index "registration_pkey";

alter table "public"."student" add constraint "student_pkey" PRIMARY KEY using index "student_pkey";

alter table "public"."term" add constraint "term_pkey" PRIMARY KEY using index "term_pkey";

alter table "public"."course" add constraint "course_code_key" UNIQUE using index "course_code_key";

alter table "public"."course_offering" add constraint "course_offering_course_id_fkey" FOREIGN KEY (course_id) REFERENCES course(id) ON UPDATE RESTRICT ON DELETE RESTRICT not valid;

alter table "public"."course_offering" validate constraint "course_offering_course_id_fkey";

alter table "public"."course_offering" add constraint "course_offering_term_id_fkey" FOREIGN KEY (term_id) REFERENCES term(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."course_offering" validate constraint "course_offering_term_id_fkey";

alter table "public"."enrollment" add constraint "registration_course_id_fkey" FOREIGN KEY (course_id) REFERENCES course(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."enrollment" validate constraint "registration_course_id_fkey";

alter table "public"."enrollment" add constraint "registration_student_id_fkey" FOREIGN KEY (student_id) REFERENCES student(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."enrollment" validate constraint "registration_student_id_fkey";

alter table "public"."student" add constraint "uq_student_gov_id" UNIQUE using index "uq_student_gov_id";

alter table "public"."term" add constraint "term_academic_year_id_fkey" FOREIGN KEY (academic_year_id) REFERENCES academic_year(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."term" validate constraint "term_academic_year_id_fkey";

grant delete on table "public"."academic_year" to "anon";

grant insert on table "public"."academic_year" to "anon";

grant references on table "public"."academic_year" to "anon";

grant select on table "public"."academic_year" to "anon";

grant trigger on table "public"."academic_year" to "anon";

grant truncate on table "public"."academic_year" to "anon";

grant update on table "public"."academic_year" to "anon";

grant delete on table "public"."academic_year" to "authenticated";

grant insert on table "public"."academic_year" to "authenticated";

grant references on table "public"."academic_year" to "authenticated";

grant select on table "public"."academic_year" to "authenticated";

grant trigger on table "public"."academic_year" to "authenticated";

grant truncate on table "public"."academic_year" to "authenticated";

grant update on table "public"."academic_year" to "authenticated";

grant delete on table "public"."academic_year" to "service_role";

grant insert on table "public"."academic_year" to "service_role";

grant references on table "public"."academic_year" to "service_role";

grant select on table "public"."academic_year" to "service_role";

grant trigger on table "public"."academic_year" to "service_role";

grant truncate on table "public"."academic_year" to "service_role";

grant update on table "public"."academic_year" to "service_role";

grant delete on table "public"."course" to "anon";

grant insert on table "public"."course" to "anon";

grant references on table "public"."course" to "anon";

grant select on table "public"."course" to "anon";

grant trigger on table "public"."course" to "anon";

grant truncate on table "public"."course" to "anon";

grant update on table "public"."course" to "anon";

grant delete on table "public"."course" to "authenticated";

grant insert on table "public"."course" to "authenticated";

grant references on table "public"."course" to "authenticated";

grant select on table "public"."course" to "authenticated";

grant trigger on table "public"."course" to "authenticated";

grant truncate on table "public"."course" to "authenticated";

grant update on table "public"."course" to "authenticated";

grant delete on table "public"."course" to "service_role";

grant insert on table "public"."course" to "service_role";

grant references on table "public"."course" to "service_role";

grant select on table "public"."course" to "service_role";

grant trigger on table "public"."course" to "service_role";

grant truncate on table "public"."course" to "service_role";

grant update on table "public"."course" to "service_role";

grant delete on table "public"."course_offering" to "anon";

grant insert on table "public"."course_offering" to "anon";

grant references on table "public"."course_offering" to "anon";

grant select on table "public"."course_offering" to "anon";

grant trigger on table "public"."course_offering" to "anon";

grant truncate on table "public"."course_offering" to "anon";

grant update on table "public"."course_offering" to "anon";

grant delete on table "public"."course_offering" to "authenticated";

grant insert on table "public"."course_offering" to "authenticated";

grant references on table "public"."course_offering" to "authenticated";

grant select on table "public"."course_offering" to "authenticated";

grant trigger on table "public"."course_offering" to "authenticated";

grant truncate on table "public"."course_offering" to "authenticated";

grant update on table "public"."course_offering" to "authenticated";

grant delete on table "public"."course_offering" to "service_role";

grant insert on table "public"."course_offering" to "service_role";

grant references on table "public"."course_offering" to "service_role";

grant select on table "public"."course_offering" to "service_role";

grant trigger on table "public"."course_offering" to "service_role";

grant truncate on table "public"."course_offering" to "service_role";

grant update on table "public"."course_offering" to "service_role";

grant delete on table "public"."enrollment" to "anon";

grant insert on table "public"."enrollment" to "anon";

grant references on table "public"."enrollment" to "anon";

grant select on table "public"."enrollment" to "anon";

grant trigger on table "public"."enrollment" to "anon";

grant truncate on table "public"."enrollment" to "anon";

grant update on table "public"."enrollment" to "anon";

grant delete on table "public"."enrollment" to "authenticated";

grant insert on table "public"."enrollment" to "authenticated";

grant references on table "public"."enrollment" to "authenticated";

grant select on table "public"."enrollment" to "authenticated";

grant trigger on table "public"."enrollment" to "authenticated";

grant truncate on table "public"."enrollment" to "authenticated";

grant update on table "public"."enrollment" to "authenticated";

grant delete on table "public"."enrollment" to "service_role";

grant insert on table "public"."enrollment" to "service_role";

grant references on table "public"."enrollment" to "service_role";

grant select on table "public"."enrollment" to "service_role";

grant trigger on table "public"."enrollment" to "service_role";

grant truncate on table "public"."enrollment" to "service_role";

grant update on table "public"."enrollment" to "service_role";

grant delete on table "public"."student" to "anon";

grant insert on table "public"."student" to "anon";

grant references on table "public"."student" to "anon";

grant select on table "public"."student" to "anon";

grant trigger on table "public"."student" to "anon";

grant truncate on table "public"."student" to "anon";

grant update on table "public"."student" to "anon";

grant delete on table "public"."student" to "authenticated";

grant insert on table "public"."student" to "authenticated";

grant references on table "public"."student" to "authenticated";

grant select on table "public"."student" to "authenticated";

grant trigger on table "public"."student" to "authenticated";

grant truncate on table "public"."student" to "authenticated";

grant update on table "public"."student" to "authenticated";

grant delete on table "public"."student" to "service_role";

grant insert on table "public"."student" to "service_role";

grant references on table "public"."student" to "service_role";

grant select on table "public"."student" to "service_role";

grant trigger on table "public"."student" to "service_role";

grant truncate on table "public"."student" to "service_role";

grant update on table "public"."student" to "service_role";

grant delete on table "public"."term" to "anon";

grant insert on table "public"."term" to "anon";

grant references on table "public"."term" to "anon";

grant select on table "public"."term" to "anon";

grant trigger on table "public"."term" to "anon";

grant truncate on table "public"."term" to "anon";

grant update on table "public"."term" to "anon";

grant delete on table "public"."term" to "authenticated";

grant insert on table "public"."term" to "authenticated";

grant references on table "public"."term" to "authenticated";

grant select on table "public"."term" to "authenticated";

grant trigger on table "public"."term" to "authenticated";

grant truncate on table "public"."term" to "authenticated";

grant update on table "public"."term" to "authenticated";

grant delete on table "public"."term" to "service_role";

grant insert on table "public"."term" to "service_role";

grant references on table "public"."term" to "service_role";

grant select on table "public"."term" to "service_role";

grant trigger on table "public"."term" to "service_role";

grant truncate on table "public"."term" to "service_role";

grant update on table "public"."term" to "service_role";


